services:
  js-app-final-app:
    image: 193668171416.dkr.ecr.us-east-2.amazonaws.com/js-app-final-app:latest
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://admin:password@mongodb:27017
    depends_on:
      - mongodb
    networks:
      - mongo-network
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
